# Generated by Django 6.0.3 on 2026-03-10 19:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='helpdeskchat',
            name='assigned_agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_helpdesk_chats', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='helpdeskmessage',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_helpdesk_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='helpdeskchat',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('waiting', 'Waiting for agent'), ('agent_open', 'With agent'), ('resolved', 'Resolved'), ('locked', 'Locked')], default='open', max_length=16),
        ),
        migrations.AlterField(
            model_name='helpdeskchat',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='helpdesk_chats', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='helpdeskmessage',
            name='role',
            field=models.CharField(choices=[('bot', 'Bot'), ('user', 'User'), ('agent', 'Agent'), ('system', 'System')], max_length=8),
        ),
    ]
